#!/usr/bin/env bash

# Note: requires bash 4.2 or later

[[ -v CONFIGURATION_DEMO_OPENSHIFT_PROCESSAUTOMATION_COMPLETED ]] && echo "Using openshift simple demo configuration" && { return || exit ; }

# assume the demo is interactive
: ${DEMO_INTERACTIVE:=true}
: ${DEMO_INTERACTIVE_PROMPT_TIMEOUT_SECONDS:=30}

# capture these configuration items from the user's environment
REDHAT_SUBSCRIPTION_USER=${REDHAT_SUBSCRIPTION_USER_MEPLEY}
REDHAT_SUBSCRIPTION_USER_PASSWORD=${REDHAT_SUBSCRIPTION_USER_MEPLEY_PASSWORD}
REDHAT_SUBSCRIPTION_USER_POOL_ID=${REDHAT_SUBSCRIPTION_USER_MEPLEY_POOL_ID}

CONTENT_SOURCE_DOCKER_IMAGES_RED_HAT_REGISTRY=registry.access.redhat.com

#                                0     1        2      3          4      5            6
DEMO_TARGET_OPENSHIFT_INSTANCES=(local rhsademo itpaas fortnebula rhtps-io nsabine-vrtx hattrick1)
# Target ITPAAS
# DEMO_TARGET_OPENSHIFT_INSTANCE=${DEMO_TARGET_OPENSHIFT_INSTANCES[2]}
# Target RHTPSIO
DEMO_TARGET_OPENSHIFT_INSTANCE=${DEMO_TARGET_OPENSHIFT_INSTANCES[4]}

# assume we don't need to expressly verify the clusters operational status
: ${OPENSHIFT_CLUSTER_VERIFY_OPERATIONAL_STATUS:=false}

# Configuration
pushd config >/dev/null 2>&1
. ./config.sh || { echo "FAILED: Could not configure generic demo environment" && exit 1 ; }
# we will be using github for this demo, so load these configuration resources 
. ./config-resources-github.sh || { echo "FAILED: Could not configure github demo resources" && exit 1 ; }
popd >/dev/null 2>&1

: ${CONFIGURATION_DEMO_OPENSHIFT_PROCESSAUTOMATION_DISPLAY:=$CONFIGURATION_DISPLAY}
# uncomment to force these scripts to display configuration information
CONFIGURATION_DEMO_OPENSHIFT_PROCESSAUTOMATION_DISPLAY=true

# Demo specific configuration items
# modify the user, or copy to new reference, then modify
OPENSHIFT_USER_RHSADEMO_MEPLEY_DEMO_PROCESSAUTOMATION=(${OPENSHIFT_USER_RHSADEMO_MEPLEY[@]})
OPENSHIFT_USER_RHSADEMO_MEPLEY_DEMO_PROCESSAUTOMATION[3]=mepley-processautomation
OPENSHIFT_USER_RHSADEMO_MEPLEY[3]=${OPENSHIFT_USER_RHSADEMO_MEPLEY_DEMO_PROCESSAUTOMATION[3]}
OPENSHIFT_USER_RHTPSIO_MEPLEY_DEMO_PROCESSAUTOMATION=(${OPENSHIFT_USER_RHTPSIO_MICHAELEPLEY_GITHUB[@]})
OPENSHIFT_USER_RHTPSIO_MEPLEY_DEMO_PROCESSAUTOMATION[3]=mepley-processautomation
OPENSHIFT_USER_RHTPSIO_MEPLEY[3]=${OPENSHIFT_USER_RHTPSIO_MEPLEY_DEMO_PROCESSAUTOMATION[3]}
OPENSHIFT_USER_ITPAAS_MEPLEY_DEMO_PROCESSAUTOMATION=(${OPENSHIFT_USER_RHSADEMO_MEPLEY[@]})
OPENSHIFT_USER_ITPAAS_MEPLEY_DEMO_PROCESSAUTOMATION[3]=mepley-processautomation
OPENSHIFT_USER_ITPAAS_MEPLEY[3]=${OPENSHIFT_USER_ITPAAS_MEPLEY_DEMO_PROCESSAUTOMATION[3]}


#OPENSHIFT_USER_REFERENCE_PRIMARY_DEFAULT="OPENSHIFT_USER_RHTPSIO_MICHAELEPLEY_GITHUB"
#OPENSHIFT_USER_PRIMARY_DEFAULT=${OPENSHIFT_USER_RHTPSIO_MICHAELEPLEY_GITHUB[0]}
#OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT=${OPENSHIFT_USER_RHTPSIO_MICHAELEPLEY_GITHUB[1]}
#OPENSHIFT_AUTH_METHOD_PRIMARY_DEFAULT=${OPENSHIFT_USER_RHTPSIO_MICHAELEPLEY_GITHUB[2]}
#OPENSHIFT_PROJECT_PRIMARY_DEFAULT=${OPENSHIFT_USER_RHTPSIO_MICHAELEPLEY_GITHUB[3]}

# NOTE: nice name but results in hostnames that are too long and exceed a 63 char limit
#APPLICATION_NAME=process-automation-manager
APPLICATION_NAME=rhpam


#OPENSHIFT_USER_REFERENCE_PRIMARY_DEFAULT
# Set the base configuration variables for the openshift-demo-processautomation
: ${OPENSHIFT_DOMAIN:=$OPENSHIFT_DOMAIN_DEFAULT}
: ${OPENSHIFT_MASTER:=$OPENSHIFT_MASTER_PRIMARY_DEFAULT}
: ${OPENSHIFT_APPS:=$OPENSHIFT_APPS_PRIMARY_DEFAULT}
: ${OPENSHIFT_PROXY_AUTH:=$OPENSHIFT_PROXY_AUTH_PRIMARY_DEFAULT}
OPENSHIFT_USER_REFERENCE=OPENSHIFT_USER_REFERENCE_PRIMARY_DEFAULT
OPENSHIFT_USER_REFERENCE=OPENSHIFT_USER_RHTPSIO_MEPLEY_DEMO_PROCESSAUTOMATION
: ${OPENSHIFT_USER:=$OPENSHIFT_USER_PRIMARY_DEFAULT}
: ${OPENSHIFT_PASSWORD:=$OPENSHIFT_USER_PRIMARY_PASSWORD_DEFAULT}
: ${OPENSHIFT_AUTH_METHOD:=$OPENSHIFT_AUTH_METHOD_PRIMARY_DEFAULT}
OPENSHIFT_PROJECT_REF="OPENSHIFT_USER_RHTPSIO_MEPLEY_DEMO_PROCESSAUTOMATION[3]"
OPENSHIFT_PROJECT=${!OPENSHIFT_PROJECT_REF}
OPENSHIFT_PROJECT_DISPLAY_NAME=${OPENSHIFT_PROJECT}
: ${OPENSHIFT_OUTPUT_FORMAT:=$OPENSHIFT_OUTPUT_FORMAT_DEFAULT}

if [ "$CONFIGURATION_DEMO_OPENSHIFT_PROCESSAUTOMATION_DISPLAY" != "false" ]; then
	echo "____________________________________________________________"
	echo "Process Automation demo for Openshift - Configuration ______"
	echo ""
	echo "	OPENSHIFT_USER_REFERENCE_PRIMARY_DEFAULT = ${OPENSHIFT_USER_REFERENCE}"
	echo "	OPENSHIFT_USER_RHTPSIO_MEPLEY_DEMO_PROCESSAUTOMATION = ${OPENSHIFT_USER_RHTPSIO_MEPLEY_DEMO_PROCESSAUTOMATION[@]}"
	echo "	OPENSHIFT_DOMAIN                        = ${OPENSHIFT_DOMAIN}"
	echo "	OPENSHIFT_PROXY_AUTH                    = ${OPENSHIFT_PROXY_AUTH}"
	echo "	OPENSHIFT_USER_REFERENCE                = ${OPENSHIFT_USER_REFERENCE}"
	echo "	OPENSHIFT_AUTH_METHOD                   = ${OPENSHIFT_AUTH_METHOD}"
	echo ""
	echo "	OPENSHIFT_MASTER                     = ${OPENSHIFT_MASTER}"
	echo "	OPENSHIFT_APPS                       = ${OPENSHIFT_APPS}"
	echo "	OPENSHIFT_PROJECT                    = ${OPENSHIFT_PROJECT}"
	echo "	OPENSHIFT_USER                       = ${OPENSHIFT_USER}"
	echo "	OPENSHIFT_PASSWORD                   = `echo ${OPENSHIFT_PASSWORD} | md5sum` (obfuscated)"
	echo "	OPENSHIFT_OUTPUT_FORMAT              = ${OPENSHIFT_OUTPUT_FORMAT}"
	echo "	REDHAT_SUBSCRIPTION_USER             = ${REDHAT_SUBSCRIPTION_USER}"
	echo "	REDHAT_SUBSCRIPTION_USER_PASSWORD    = ${REDHAT_SUBSCRIPTION_USER_PASSWORD}"
	echo "	REDHAT_SUBSCRIPTION_USER_PASSWORD    = `echo ${REDHAT_SUBSCRIPTION_USER_PASSWORD} | md5sum` (obfuscated)"
	echo "	REDHAT_SUBSCRIPTION_USER_POOL_ID     = ${REDHAT_SUBSCRIPTION_USER_POOL_ID}"
	echo "	CONTENT_SOURCE_DOCKER_IMAGES_RED_HAT_REGISTRY = ${CONTENT_SOURCE_DOCKER_IMAGES_RED_HAT_REGISTRY}"
	echo "____________________________________________________________"
fi

CONFIGURATION_DEMO_OPENSHIFT_PROCESSAUTOMATION_COMPLETED=true
