apiVersion: v1
kind: Template
labels:
  template: rhpam-install
  group: rhpam-install
metadata:
  annotations:
    iconClass: icon-jenkins
    tags: instant-app,rhpam
  name: rhpam-install
message: "Use the following credentials for login:\nJenkins: use your OpenShift credentials\nNexus: admin/admin123\nSonarQube: admin/admin\nGogs Git Server: gogs/gogs"
parameters:
- displayName: TARGET project name
  value: dev
  name: TARGET_NAMESPACE
  required: true
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: rhpam-demo-installer
  spec:
    activeDeadlineSeconds: 400
    completions: 1
    parallelism: 1
    template:
      spec:
        containers:
        - env:
          - name: TARGET_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          command:
          - /bin/bash
          - -x
          - -c
          - |
            # yum install -y unzip
            TEMPDIR=`mktemp -d`
            curl -s -k -L -O https://github.com/jbossdemocentral/rhpam7-install-demo/archive/master.zip
            unzip master.zip -d ${TEMPDIR}
            pushd ${TEMPDIR}/rhpam7-install-demo-master
            ${TEMPDIR}/rhpam7-install-demo-master/init-openshift.sh
          # image: openshift/origin:v3.9.0
          # image: docker-registry.default.svc:5000/openshift/java
          # image: docker-registry.default.svc:5000/openshift/jenkins-slave-maven-rhel7
          # image: docker-registry.default.svc:5000/mepley-processautomation/rhpam-installer
          image: docker-registry.default.svc:5000/mepley-processautomation/rhpam-installer 
          name: rhpam-demo-installer-job
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        restartPolicy: Never